{
 "title": "open5gs_metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Liczba sesji AMF",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "amf_session{service=\"open5gs-amf-metrics\",namespace=\"default\"}",
     "legendFormat": "AMF Session"
    }
   ]
  },
  {
   "title": "Zuzycie CPU dla UPF",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kube_pod_container_resource_limits{pod=~\"open5gs-upf.*\", resource=\"cpu\", namespace=\"default\"}",
     "legendFormat": "Zuzycie CPU"
    }
   ]
  },
  {
   "title": "RAM limit UPF",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kube_pod_container_resource_limits{pod=~\"open5gs-upf.*\", resource=\"memory\", namespace=\"default\"}",
     "legendFormat": "RAM"
    }
   ]
  }
 ]
}